# Generated by Django 5.0.6 on 2024-08-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
