name: CI/CD Pipeline for E2E Tests

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: http://localhost:8000
      DJANGO_SETTINGS_MODULE: audio_participation_backend.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print environment information
        run: |
          echo "Python version:"
          python --version
          echo "Node.js version:"
          node --version
          echo "npm version:"
          npm --version

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r audio_participation_backend/requirements.txt

      - name: Build backend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest -f audio_participation_backend/Dockerfile audio_participation_backend/
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest

      - name: Build frontend Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest -f audio-participation-frontend/Dockerfile audio-participation-frontend/
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f .github/workflows/deployment.yaml
          kubectl apply -f .github/workflows/service.yaml

      - name: Run E2E Tests in Kubernetes
        run: |
          kubectl apply -f .github/workflows/e2e-tests.yaml

      - name: Collect Test Results
        run: |
          kubectl logs -l job-name=myapp-e2e-tests > e2e-test-results.log

      - name: Upload Test Results
        uses: actions/upload-artifact@v2
        with:
          name: e2e-test-results
          path: e2e-test-results.log
        continue-on-error: true
