name: CI/CD Pipeline for E2E Tests

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: http://localhost:8000
      DJANGO_SETTINGS_MODULE: audio_participation_backend.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Print environment information
        run: |
          echo "Python version:"
          python --version
          echo "Node.js version:"
          node --version
          echo "npm version:"
          npm --version

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r audio_participation_backend/audio_participation_backend/requirements.txt

      - name: Set up Django environment
        run: |
          cd audio_participation_backend
          mkdir -p logs
          python manage.py check

      - name: Apply migrations
        run: |
          cd audio_participation_backend
          python manage.py migrate

      - name: Verify database state
        run: |
          cd audio_participation_backend
          python manage.py dumpdata > db_state.json
          echo "Database state:"
          cat db_state.json

      - name: Start Django server
        run: |
          cd audio_participation_backend
          python manage.py runserver 0.0.0.0:8000 &

      - name: Print backend logs
        run: |
          sleep 10
          cat audio_participation_backend/logs/django.log

      - name: Wait for backend to be ready
        run: |
          sudo apt-get install -y curl
          until curl --output /dev/null --silent --head --fail http://localhost:8000; do
            echo 'Waiting for backend...'
            sleep 10
          done

      - name: Install frontend dependencies
        run: |
          cd audio-participation-frontend
          npm install

      - name: Start frontend server
        env:
          CI: true
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
        run: |
          cd audio-participation-frontend
          echo "REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}" > .env
          npm start &

      - name: Print frontend logs
        run: |
          sleep 10
          if [ -d "audio-participation-frontend/logs" ]; then
            cat audio-participation-frontend/logs/*.log
          else
            echo "Frontend logs directory not found"
          fi

      - name: Wait for frontend to be ready
        run: |
          until curl --output /dev/null --silent --head --fail http://localhost:3000; do
            echo 'Waiting for frontend...'
            sleep 10
          done

      - name: Check backend server status
        run: |
          curl -I http://localhost:8000

      - name: Check frontend server status
        run: |
          curl -I http://localhost:3000

      - name: Check frontend to backend connectivity
        run: |
          curl -I http://localhost:3000/api/healthcheck

      - name: Check environment variables
        run: |
          echo "REACT_APP_API_URL: $REACT_APP_API_URL"
          echo "DJANGO_SETTINGS_MODULE: $DJANGO_SETTINGS_MODULE"

      - name: Install Cypress dependencies
        run: |
          cd audio-participation-frontend
          npm install cypress

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: http://localhost:3000
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
        run: |
          cd audio-participation-frontend
          npx cypress run --config defaultCommandTimeout=120000

      - name: List Cypress videos
        run: ls -R audio-participation-frontend/cypress/videos
        continue-on-error: true

      - name: List Cypress screenshots
        run: ls -R audio-participation-frontend/cypress/screenshots
        continue-on-error: true

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: audio-participation-frontend/cypress/videos/**/*.mp4
        continue-on-error: true

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: audio-participation-frontend/cypress/screenshots/**/*.png
        continue-on-error: true

      - name: Upload Cypress failed logs
        uses: actions/upload-artifact@v2
        with:
          name: cypress-failed-logs
          path: audio-participation-frontend/cypress-failed-log.txt
        continue-on-error: true

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest -f audio_participation_backend/Dockerfile .
          docker build -t ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest -f audio-participation-frontend/Dockerfile .
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-backend:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/myapp-frontend:latest


      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker

      - name: Set up kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          kubectl config use-context minikube

      - name: Deploy to Minikube
        run: |
          kubectl apply -f deployment.yaml
          kubectl apply -f service.yaml
