name: CI/CD Pipeline for E2E Tests

on:
  pull_request:
    branches:
      - main
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      REACT_APP_API_URL: http://localhost:8000
      DJANGO_SETTINGS_MODULE: audio_participation_backend.settings

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10.5'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install backend dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r audio_participation_backend/requirements.txt

      - name: Apply migrations and start Django server
        run: |
          cd audio_participation_backend
          python manage.py migrate
          python manage.py runserver 0.0.0.0:8000 &
        env:
          DJANGO_SETTINGS_MODULE: ${{ env.DJANGO_SETTINGS_MODULE }}

      - name: Install frontend dependencies
        run: |
          cd audio-participation-frontend
          npm install

      - name: Start frontend server
        env:
          CI: true
          REACT_APP_API_URL: ${{ env.REACT_APP_API_URL }}
        run: |
          cd audio-participation-frontend
          echo "REACT_APP_API_URL=${{ env.REACT_APP_API_URL }}" > .env
          npm start &

      - name: Wait for servers to be ready
        run: |
          sleep 30  # Increase if servers need more time to start
          curl -I http://localhost:8000
          curl -I http://localhost:3000

      - name: Install Cypress dependencies
        run: |
          cd audio-participation-frontend
          npm install cypress

      - name: Run Cypress tests
        env:
          CYPRESS_BASE_URL: http://localhost:3000
        run: |
          cd audio-participation-frontend
          npx cypress run --config defaultCommandTimeout=120000

      - name: Upload Cypress Videos
        uses: actions/upload-artifact@v2
        with:
          name: cypress-videos
          path: audio-participation-frontend/cypress/videos/**/*.mp4
        continue-on-error: true

      - name: Upload Cypress Screenshots
        uses: actions/upload-artifact@v2
        with:
          name: cypress-screenshots
          path: audio-participation-frontend/cypress/screenshots/**/*.png
        continue-on-error: true

      - name: Upload Cypress failed logs
        uses: actions/upload-artifact@v2
        with:
          name: cypress-failed-logs
          path: audio-participation-frontend/cypress-failed-log.txt
        continue-on-error: true
