apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: backend
        image: ayongelvis/myapp-backend:latest
        ports:
        - containerPort: 8000
      - name: frontend
        image: ayongelvis/myapp-frontend:latest
        ports:
        - containerPort: 3000
