name: Deploy to Production

on:
  workflow_run:
    workflows: ["CI/CD Pipeline for E2E Tests"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up Kubernetes context
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x ./kubectl
          sudo mv ./kubectl /usr/local/bin/kubectl
          minikube start --driver=docker
          minikube kubectl -- get pods -A

      - name: Deploy to Production
        run: |
          kubectl apply -f .github/workflows/deployment.yaml
          kubectl apply -f .github/workflows/service.yaml
