apiVersion: batch/v1
kind: Job
metadata:
  name: myapp-e2e-tests
spec:
  template:
    spec:
      containers:
      - name: e2e-tests
        image: cypress/included:9.3.1
        command: ["npx", "cypress", "run"]
        env:
        - name: CYPRESS_BASE_URL
          value: "http://myapp-frontend-service.default.svc.cluster.local"
      restartPolicy: Never
  backoffLimit: 4
